In [1]:
import pandas as pd
import numpy as np

# Optionnel : pour voir toutes les colonnes lors de l'affichage
pd.set_option('display.max_columns', None)

# Nettoyage du dataset

Ce notebook contient le code pour nettoyer le dataset de données sur les retards de trains.

In [2]:
file_path = "project_dataset.csv"
df = pd.read_csv(file_path, sep=";", encoding="utf-8")

print(f"Nombre de lignes initiales : {len(df)}")
df.head()

Nombre de lignes initiales : 12070

,Date,Service,Gare de départ,Gare d'arrivée,Durée moyenne du trajet,Nombre de circulations prévues,Nombre de trains annulés,Commentaire annulations,Nombre de trains en retard au départ,Retard moyen des trains en retard au départ,Retard moyen de tous les trains au départ,Commentaire retards au départ,Nombre de trains en retard à l'arrivée,Retard moyen des trains en retard à l'arrivée,Retard moyen de tous les trains à l'arrivée,Commentaire retards à l'arrivée,Nombre trains en retard > 15min,Retard moyen trains en retard > 15 (si liaison concurrencée par vol),Nombre trains en retard > 30min,Nombre trains en retard > 60min,Prct retard pour causes externes,Prct retard pour cause infrastructure,Prct retard pour cause gestion trafic,Prct retard pour cause matériel roulant,Prct retard pour cause gestion en gare et réutilisation de matériel,"Prct retard pour cause prise en compte voyageurs (affluence, gestions PSH, correspondances)"
0,2018-01,National,BORDEAUX ST JEAN,PARIS MONTPARNASSE,141.0,870,5.0,NaN,289.0,11.24780854,3.693179191,NaN,147.0,28.43673469,6.511117534,NaN,110.0,6.51,44.0,8.0,36.13445378,31.09243697,10.92436975,15.96638655,"5,04",0.840336134
1,2018-01,National,LE MANS,PARIS MONTPARNASSE,56.0,406.0,1.0,NaN,213.0,8.479968701,4.567119342,NaN,105.0,18.049,5.363539095,"Ce mois-ci, l'OD a été touchée par les inciden...",32.0,5.363539095,9.0,4.0,20.0,35.0,16.66666667,16.66666667,8.333333333,3.333333333
2,2018-01,National,PARIS MONTPARNASSE,LA ROCHELLE VILLE,166.0,226.0,0.0,NaN,21.0,6.23968254,0.286283186,NaN,19.0,24.73684211,2.938053097,NaN,11.0,2.938053097,6.0,1.0,22.22222222,27.77777778,16.66666667,16.66666667,5.555555556,11.11111111
3,2018-01,National,PARIS MONTPARNASSE,NANTES,216.21,508.0,3.0,NaN,71.0,7.235211268,0.98,NaN,58.0,33.72643678,5.292211221,NaN,39.0,5.292211221,18.0,NaN,33.33333333,22.22222222,16.66666667,20.37037037,5.555555556,1.851851852
4,2018-01,National,POITIERS,PARIS MONTPARNASSE,94.0,472.0,4.0,NaN,224.0,6.784672619,3.229700855,NaN,89.0,14.59269663,4.882371795,NaN,42.0,4.882371795,10.0,0.0,15.78947368,45.61403509,NaN,15.78947368,1.754385965,1.754385965

In [3]:
# On ne garde que les lignes où la Date commence par un chiffre (Année ou Jour)
# Cela élimine les lignes commençant par "Le ", "Note", etc.
df = df[df['Date'].astype(str).str.contains(r'^\d', na=False, regex=True)]

print(f"Nombre de lignes après filtrage des commentaires : {len(df)}")

Nombre de lignes après filtrage des commentaires : 12010

In [4]:
initial_count = len(df)
df = df.drop_duplicates()
print(f"Doublons supprimés : {initial_count - len(df)}")

Doublons supprimés : 173

In [5]:
numeric_cols = [
    "Durée moyenne du trajet", "Nombre de circulations prévues", "Nombre de trains annulés",
    "Nombre de trains en retard au départ", "Retard moyen des trains en retard au départ",
    "Retard moyen de tous les trains au départ", "Nombre de trains en retard à l'arrivée",
    "Retard moyen des trains en retard à l'arrivée", "Retard moyen de tous les trains à l'arrivée",
    "Nombre trains en retard > 15min", "Retard moyen trains en retard > 15 (si liaison concurrencée par vol)",
    "Nombre trains en retard > 30min", "Nombre trains en retard > 60min",
    "Prct retard pour causes externes", "Prct retard pour cause infrastructure",
    "Prct retard pour cause gestion trafic", "Prct retard pour cause matériel roulant",
    "Prct retard pour cause gestion en gare et réutilisation de matériel",
    "Prct retard pour cause prise en compte voyageurs (affluence, gestions PSH, correspondances)"
]

# Nettoyage et conversion numérique
for col in numeric_cols:
    df[col] = df[col].astype(str).str.replace(",", ".").replace("-", np.nan)
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Conversion de la date (format flexible)
df["Date"] = pd.to_datetime(df["Date"], format="mixed", errors="coerce")

# Suppression des éventuelles lignes où la date n'a pas pu être convertie
df = df.dropna(subset=['Date'])

# Création des colonnes pour faciliter l'analyse temporelle
df["Année"] = df["Date"].dt.year.astype(int)
df["Mois"] = df["Date"].dt.month.astype(int)

df.head()

,Date,Service,Gare de départ,Gare d'arrivée,Durée moyenne du trajet,Nombre de circulations prévues,Nombre de trains annulés,Commentaire annulations,Nombre de trains en retard au départ,Retard moyen des trains en retard au départ,Retard moyen de tous les trains au départ,Commentaire retards au départ,Nombre de trains en retard à l'arrivée,Retard moyen des trains en retard à l'arrivée,Retard moyen de tous les trains à l'arrivée,Commentaire retards à l'arrivée,Nombre trains en retard > 15min,Retard moyen trains en retard > 15 (si liaison concurrencée par vol),Nombre trains en retard > 30min,Nombre trains en retard > 60min,Prct retard pour causes externes,Prct retard pour cause infrastructure,Prct retard pour cause gestion trafic,Prct retard pour cause matériel roulant,Prct retard pour cause gestion en gare et réutilisation de matériel,"Prct retard pour cause prise en compte voyageurs (affluence, gestions PSH, correspondances)",Année,Mois
0,2018-01-01,National,BORDEAUX ST JEAN,PARIS MONTPARNASSE,141.00,870.0,5.0,NaN,289.0,11.247809,3.693179,NaN,147.0,28.436735,6.511118,NaN,110.0,6.510000,44.0,8.0,36.134454,31.092437,10.924370,15.966387,5.040000,0.840336,2018,1
1,2018-01-01,National,LE MANS,PARIS MONTPARNASSE,56.00,406.0,1.0,NaN,213.0,8.479969,4.567119,NaN,105.0,18.049000,5.363539,"Ce mois-ci, l'OD a été touchée par les inciden...",32.0,5.363539,9.0,4.0,20.000000,35.000000,16.666667,16.666667,8.333333,3.333333,2018,1
2,2018-01-01,National,PARIS MONTPARNASSE,LA ROCHELLE VILLE,166.00,226.0,0.0,NaN,21.0,6.239683,0.286283,NaN,19.0,24.736842,2.938053,NaN,11.0,2.938053,6.0,1.0,22.222222,27.777778,16.666667,16.666667,5.555556,11.111111,2018,1
3,2018-01-01,National,PARIS MONTPARNASSE,NANTES,216.21,508.0,3.0,NaN,71.0,7.235211,0.980000,NaN,58.0,33.726437,5.292211,NaN,39.0,5.292211,18.0,NaN,33.333333,22.222222,16.666667,20.370370,5.555556,1.851852,2018,1
4,2018-01-01,National,POITIERS,PARIS MONTPARNASSE,94.00,472.0,4.0,NaN,224.0,6.784673,3.229701,NaN,89.0,14.592697,4.882372,NaN,42.0,4.882372,10.0,0.0,15.789474,45.614035,NaN,15.789474,1.754386,1.754386,2018,1

In [6]:
# Conversion des colonnes de type 'object' en 'string'
df = df.astype({col: 'string' for col in df.select_dtypes(include='object').columns})

# Vérification
print(df.dtypes)

Date                                                                                           datetime64[ns]
Service                                                                                        string[python]
Gare de départ                                                                                 string[python]
Gare d'arrivée                                                                                 string[python]
Durée moyenne du trajet                                                                               float64
Nombre de circulations prévues                                                                        float64
Nombre de trains annulés                                                                              float64
Commentaire annulations                                                                        string[python]
Nombre de trains en retard au départ                                                                  float64
Retard moyen des trains en retard au départ                                                           float64
Retard moyen de tous les trains au départ                                                             float64
Commentaire retards au départ                                                                  string[python]
Nombre de trains en retard à l'arrivée                                                                float64
Retard moyen des trains en retard à l'arrivée                                                         float64
Retard moyen de tous les trains à l'arrivée                                                           float64
Commentaire retards à l'arrivée                                                                string[python]
Nombre trains en retard > 15min                                                                       float64
Retard moyen trains en retard > 15 (si liaison concurrencée par vol)                                  float64
Nombre trains en retard > 30min                                                                       float64
Nombre trains en retard > 60min                                                                       float64
Prct retard pour causes externes                                                                      float64
Prct retard pour cause infrastructure                                                                 float64
Prct retard pour cause gestion trafic                                                                 float64
Prct retard pour cause matériel roulant                                                               float64
Prct retard pour cause gestion en gare et réutilisation de matériel                                   float64
Prct retard pour cause prise en compte voyageurs (affluence, gestions PSH, correspondances)           float64
Année                                                                                                   int64
Mois                                                                                                    int64
dtype: object

In [7]:
# Remplissage des numériques par 0
df[numeric_cols] = df[numeric_cols].fillna(0)

# Remplissage des commentaires textuels
comment_cols = [
    "Commentaire annulations", 
    "Commentaire retards au départ", 
    "Commentaire retards à l'arrivée"
]
for col in comment_cols:
    df[col] = df[col].fillna("Non communiqué")

print("État final des valeurs manquantes :")
print(df.isnull().sum().sum())

État final des valeurs manquantes :
352

In [ ]:
output_file = "cleaned_dataset.csv"
df.to_csv(output_file, index=False, sep=";", encoding="utf-8")

print(f"Dataset nettoyé et prêt pour l'analyse : {output_file}")
# Affiche le type de chaque colonne et l'occupation mémoire
print(df.info())

✅ Dataset nettoyé et prêt pour l'analyse : cleaned_dataset.csv
<class 'pandas.core.frame.DataFrame'>
Index: 11837 entries, 0 to 12060
Data columns (total 28 columns):
 #   Column                                                                                       Non-Null Count  Dtype
---  ------                                                                                       --------------  -----
 0   Date                                                                                         11837 non-null  datetime64[ns]
 1   Service                                                                                      11602 non-null  string
 2   Gare de départ                                                                               11779 non-null  string
 3   Gare d'arrivée                                                                               11778 non-null  string
 4   Durée moyenne du trajet                                                                      11837 non-null  float64
 5   Nombre de circulations prévues                                                               11837 non-null  float64
 6   Nombre de trains annulés                                                                     11837 non-null  float64
 7   Commentaire annulations                                                                      11837 non-null  string
 8   Nombre de trains en retard au départ                                                         11837 non-null  float64
 9   Retard moyen des trains en retard au départ                                                  11837 non-null  float64
 10  Retard moyen de tous les trains au départ                                                    11837 non-null  float64
 11  Commentaire retards au départ                                                                11837 non-null  string
 12  Nombre de trains en retard à l'arrivée                                                       11837 non-null  float64
 13  Retard moyen des trains en retard à l'arrivée                                                11837 non-null  float64
 14  Retard moyen de tous les trains à l'arrivée                                                  11837 non-null  float64
 15  Commentaire retards à l'arrivée                                                              11837 non-null  string
 16  Nombre trains en retard > 15min                                                              11837 non-null  float64
 17  Retard moyen trains en retard > 15 (si liaison concurrencée par vol)                         11837 non-null  float64
 18  Nombre trains en retard > 30min                                                              11837 non-null  float64
 19  Nombre trains en retard > 60min                                                              11837 non-null  float64
 20  Prct retard pour causes externes                                                             11837 non-null  float64
 21  Prct retard pour cause infrastructure                                                        11837 non-null  float64
 22  Prct retard pour cause gestion trafic                                                        11837 non-null  float64
 23  Prct retard pour cause matériel roulant                                                      11837 non-null  float64
 24  Prct retard pour cause gestion en gare et réutilisation de matériel                          11837 non-null  float64
 25  Prct retard pour cause prise en compte voyageurs (affluence, gestions PSH, correspondances)  11837 non-null  float64
 26  Année                                                                                        11837 non-null  int64
 27  Mois                                                                                         11837 non-null  int64
dtypes: datetime64[ns](1), float64(19), int64(2), string(6)
memory usage: 2.6 MB
None